### ISSUE TITLE
Overlap backward phrase

### ISSUE THREAD

**Issue by ducviet00** [HKBU-HPML/MG-WFBP#3]
Hi, I've read the paper and I saw that mentions an overlapping time in gradient exchange and backward phrase.
https://imgur.com/jIFmEN8

I explored your code but I did not see anything about it.
Can you point it out?

**Comment by shyhuai** [comment]
Hi, there is a daemon thread handling the gradient exchange in Horovod, in which the gradient computations are hooked with ``https://github.com/HKBU-HPML/MG-WFBP/blob/master/distributed_optimizer.py#L137''. In such a way, when one tensor's gradient has been calculated, the tensor is pushed to the daemon thread for communication, so that the communication and computation can be done in parallel.

**Comment by ducviet00** [comment]
Thank you very much !!
